---
title: "data exploration"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(here)
library(janitor)
```


```{r}
food_data<-read.csv("food and covid data/Food_Supply_Quantity_kg_Data_general_notation.csv")
food_data
```
```{r}
food_data %>% 
  group_by(Country) %>%
  ggplot(aes(Obesity,Deaths))+geom_point()+geom_smooth(method = lm)
```
```{r}
food_data %>% 
  group_by(Country) %>%
  ggplot(aes(Vegetal.Products,Deaths))+geom_point()+geom_smooth(method = lm) +
      labs(title = "Vegtable Products vs COVID-19 Deaths",x="Supply of Vegtable Products", y="Deaths")
```
```{r}
food_data %>% 
  group_by(Country) %>%
  ggplot(aes(Meat,Deaths))+geom_point()+geom_smooth(method = lm)
```
```{r}
food_data %>% 
  select(Alcoholic.Beverages, Country) %>% 
  arrange(desc(Alcoholic.Beverages))
```

```{r}
food_data %>% 
  group_by(Country) %>%
  ggplot(aes(Obesity,Deaths))+
  geom_point()+
  geom_smooth(method = lm, formula = y ~ x)+
  labs(title = "Obesity vs COVID-19 Deaths",
       x="Obesity",
       y="Deaths")+
  stat_regline_equation()
```
```{r}
#install.packages("ggpubr")
library(ggpubr)
```




```{r}
food_data %>% 
  select(Obesity,Country) %>% 
  arrange(desc(Obesity))
```
```{r}
island_food_data<- food_data %>% 
  filter(Country== "Samoa"|
           Country=="United Kingdom"|
           Country=="Fiji" |
           Country=="Japan"|
           Country=="Australia"|
           Country=="New Zealand"|
           Country=="Kiribati"|
           Country=="Iceland"|
           Country=="Philippines") %>% 
   mutate(Island= TRUE)
island_food_data
```


```{r}
non_island_food_data<- food_data %>% 
   filter( Country!="Australia",
           Country!="Samoa",
           Country!="United Kingdom",
           Country!="New Zealand",
           Country!="Kiribati",
           Country!="Iceland",
           Country!="Philippines",
           Country!="Fiji",
           Country!="Japan" ) %>%
  mutate(Island= FALSE)
non_island_food_data
```
```{r}
food_data %>% 
  filter(Obesity>37) %>% 
  select(Country, Confirmed, Deaths, Recovered)
```

```{r}
island_food_complete <- rbind(non_island_food_data,
                              island_food_data)
```
```{r}
island_food_complete %>% 
  select(Country, Undernourished) %>% 
  arrange(desc(Undernourished))
```

```{r}
island_food_complete %>% 
  ggplot(aes(Obesity,Deaths,color=Island))+
  geom_point()+
  geom_smooth(method = lm)+
  labs(title = "Obesity vs COVID-19 Deaths",
       x="Obesity",
       y="Deaths")
```
```{r}
island_food_complete %>% 
  filter(Country!= "United Kingdom") %>% 
  ggplot(aes(Obesity,Deaths,color=Island))+
  geom_point()+
  geom_smooth(method = lm)+ 
  labs(title = "Obesity vs COVID-19 Deaths"
      ,x="Obesity",
      y="Deaths")+
  stat_regline_equation()
```


```{r}
island_food_complete %>% 
  mutate(recovery_death_ratio=Recovered/Deaths) %>% 
  group_by(Island) %>% 
  filter(recovery_death_ratio!= Inf) %>% 
  summarise(mean_reco_death_ratio=mean(recovery_death_ratio,na.rm=T)) %>% 
  ggplot(aes(Island,mean_reco_death_ratio, fill= Island))+
  geom_col(color = "black")+
  labs(title = "Recovered/Deaths Ratio Between Land Types",
       x=NULL,
       y=" Mean of Recovered/Deaths")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```
```{r}
island_food_complete %>% 
  mutate(recovery_death_ratio=Recovered/Deaths) %>% 
  filter(recovery_death_ratio!= Inf,
         recovery_death_ratio < 300) %>% 
  ggplot(aes(Island, recovery_death_ratio,
             fill=Island))+
  geom_boxplot(outlier.alpha = 0.6,color = "black")+
  labs(title = "Recovered/Deaths Between Land Types",
       x=NULL,
       y=" Recovered/Deaths")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

```{r}
well_nourished_countries<-food_data %>% 
  filter(Undernourished== "<2.5") %>% 
  cbind(2.5) %>% 
  mutate(Undernourished_numeric= mean(2.5)) %>% 
  select(!"2.5")
```

```{r}
food_experiment<- food_data %>% 
  filter(Undernourished != "<2.5")

```
```{r}
  food_experiment<-food_experiment %>% 
  mutate(Undernourished_numeric=as.numeric(as.character(food_experiment$Undernourished)))
  
```
```{r}
nourishment_complete <- rbind(food_experiment, well_nourished_countries)
nourishment_complete
```
```{r}
is.numeric(nourishment_complete$Undernourished_numeric)
```

```{r}
nourishment_complete <- nourishment_complete %>% 
             mutate(nourishment_catagory= case_when(Undernourished_numeric <=2.5 ~ "low undernourishment",
                                              Undernourished_numeric > 2.5 & Undernourished_numeric <= 15 ~ "medium undernourishment",
                                              Undernourished_numeric > 15 ~ "high undernourishment"))
nourishment_complete
```
```{r}
nourishment_complete %>% 
  ggplot(aes(Undernourished_numeric, Obesity))+
  geom_point()+geom_smooth(method = lm)+
  labs(title = "Obesity vs Undernourishment",
       x="Undernourishment",
       y="Obesity")
```
```{r}
nourishment_complete
```

```{r}
nourishment_complete %>%
  mutate(confirmed_death_ratio=Deaths/Confirmed) %>%
  ggplot(aes(reorder(Country,confirmed_death_ratio),
             confirmed_death_ratio,
             fill=nourishment_catagory))+
  geom_col()+
  labs(title = "COVID Deaths / Confirmed Cases: by Nourishment Catagory",
       x=NULL,
       y=" Death/Confirmed")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```
```{r}
nourishment_complete %>% 
  mutate(confirmed_death_ratio=Deaths/Confirmed) %>%
  filter(confirmed_death_ratio>0.1)
```

```{r}
nourishment_complete %>%
  mutate(confirmed_death_ratio=Deaths/Confirmed) %>%
  group_by(nourishment_catagory) %>% 
  summarise(mean_confirmed_death_ratio= mean(confirmed_death_ratio,
                                             na.rm=T)) %>% 
  ggplot(aes(reorder(nourishment_catagory,mean_confirmed_death_ratio),
             mean_confirmed_death_ratio, fill=nourishment_catagory))+
  geom_col(color = "black")+
  labs(title = "Average of COVID Deaths / Confirmed Cases: by Nourishment Category",
       x=NULL, 
       y=" Mean of Deaths/Confirmed")+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```










